"""+ commands

Revision ID: f45bf1f74df6
Revises: b8d44b1679d1
Create Date: 2018-10-17 10:09:36.696534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45bf1f74df6'
down_revision = 'b8d44b1679d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.Column('user', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_ts'), 'command', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_ts'), table_name='command')
    op.drop_table('command')
    # ### end Alembic commands ###
